apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-injecternitiator
  name: file-injecternitiator
  namespace: fortuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-injecternitiator
  template:
    metadata:
      labels:
        app: file-injecternitiator
    spec:
      containers:
      - name: fortuna
        image: filefrog/o-fortuna:latest
        command: ["/bin/sh", "-c"]
        args: ["cp /new_file/new.file /fortunes.js && node index.js"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: injected-secret-volume
          mountPath: /new_file
      initContainers:
      - name: variable-swap
        image: tomvoboril/variable-swap
        env:
        - name: OLD_FILE
          value: /old.file
        - name: NEW_FILE
          value: /new_file/new.file
        envFrom:
        - secretRef:
            name: key-token-new
        volumeMounts:
        - name: injected-secret-volume
          mountPath: /new_file
        - name: old-file
          mountPath: /old.file
          subPath: old.file
      volumes:
      - name: injected-secret-volume
        emptyDir: {}
      - name: old-file
        configMap:
          name: old-file
          defaultMode: 0744
