apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-injecternitiator
  name: file-injecternitiator
  namespace: fortuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-injecternitiator
  template:
    metadata:
      labels:
        app: file-injecternitiator
    spec:
      containers:
      - name: fortuna
        image: filefrog/o-fortuna:latest
        command: ["/bin/sh", "-c"]
        args: ["node index.js"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: injected-secret-volume
          mountPath: /fortunes.js
          subPath: fortunes.js
      initContainers:
      - name: key-replacer
        image: python
        envFrom:
        - secretRef:
            name: key-token-new
        - configMapRef:
            name: key-token
        env:
        - name: outpt_file
          value: /newstuff/fortunes.js
        - name: repo
          value: https://github.com/jhunt/o-fortuna.git
        - name: inpt_file
          value: /o-fortuna/fortunes.js
        command: ["/bin/sh", "-c", "/app/key-replacer.sh"]
        volumeMounts:
        - name: key-replacer
          mountPath: /app
        - name: injected-secret-volume
          mountPath: /newstuff
      volumes:
      - name: injected-secret-volume
        emptyDir: {}
      - name: key-replacer
        configMap:
          name: key-replacer
          defaultMode: 0744
