apiVersion: v1
kind: Service
metadata:
  name: file-injecternitiator-node
  namespace: fortuna
spec:
  type: NodePort
  selector:
    app: file-injecternitiator
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
